language: python

python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - pip install -r dev-requirements.txt

before_script:
    - "pep8 --ignore=E501 ."

script: py.test

after_success:
    - coveralls